// flow-typed signature: f89f64a2056f044f4f41c0c1678b95d8
// flow-typed version: <<STUB>>/geojson-polygon-center_v0.0.0/flow_v0.92.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'geojson-polygon-center'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'geojson-polygon-center' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'geojson-polygon-center/index' {
  declare module.exports: $Exports<'geojson-polygon-center'>;
}
declare module 'geojson-polygon-center/index.js' {
  declare module.exports: $Exports<'geojson-polygon-center'>;
}
