// flow-typed signature: 78b8cb9d3f444541dd2ab7f6266953e5
// flow-typed version: <<STUB>>/google-libphonenumber_v3.2.5/flow_v0.92.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'google-libphonenumber'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'google-libphonenumber' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'google-libphonenumber/dist/libphonenumber' {
  declare module.exports: any;
}

// Filename aliases
declare module 'google-libphonenumber/dist/libphonenumber.js' {
  declare module.exports: $Exports<'google-libphonenumber/dist/libphonenumber'>;
}
