// flow-typed signature: c4cb9de13d2c741444e27e7c049872bb
// flow-typed version: <<STUB>>/i18n-js_v3.3.0/flow_v0.92.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'i18n-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'i18n-js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'i18n-js/app/assets/javascripts/i18n' {
  declare module.exports: any;
}

// Filename aliases
declare module 'i18n-js/app/assets/javascripts/i18n.js' {
  declare module.exports: $Exports<'i18n-js/app/assets/javascripts/i18n'>;
}
