// flow-typed signature: 1d8eaffce8bee58804be76dcc8102e29
// flow-typed version: <<STUB>>/react-native-file-viewer_v2.0.1/flow_v0.92.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-file-viewer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-file-viewer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-native-file-viewer/index' {
  declare module.exports: $Exports<'react-native-file-viewer'>;
}
declare module 'react-native-file-viewer/index.js' {
  declare module.exports: $Exports<'react-native-file-viewer'>;
}
