// flow-typed signature: e7c94133240fedf6a4ceb72bf1f6886c
// flow-typed version: <<STUB>>/react-native-floating-action_v1.19.1/flow_v0.92.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-floating-action'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-floating-action' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-floating-action/src/AddIcon' {
  declare module.exports: any;
}

declare module 'react-native-floating-action/src/FloatingAction' {
  declare module.exports: any;
}

declare module 'react-native-floating-action/src/FloatingActionItem' {
  declare module.exports: any;
}

declare module 'react-native-floating-action/src' {
  declare module.exports: any;
}

declare module 'react-native-floating-action/src/utils/color' {
  declare module.exports: any;
}

declare module 'react-native-floating-action/src/utils/platform' {
  declare module.exports: any;
}

declare module 'react-native-floating-action/src/utils/touchable' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-floating-action/index' {
  declare module.exports: $Exports<'react-native-floating-action'>;
}
declare module 'react-native-floating-action/index.js' {
  declare module.exports: $Exports<'react-native-floating-action'>;
}
declare module 'react-native-floating-action/src/AddIcon.js' {
  declare module.exports: $Exports<'react-native-floating-action/src/AddIcon'>;
}
declare module 'react-native-floating-action/src/FloatingAction.js' {
  declare module.exports: $Exports<'react-native-floating-action/src/FloatingAction'>;
}
declare module 'react-native-floating-action/src/FloatingActionItem.js' {
  declare module.exports: $Exports<'react-native-floating-action/src/FloatingActionItem'>;
}
declare module 'react-native-floating-action/src/index' {
  declare module.exports: $Exports<'react-native-floating-action/src'>;
}
declare module 'react-native-floating-action/src/index.js' {
  declare module.exports: $Exports<'react-native-floating-action/src'>;
}
declare module 'react-native-floating-action/src/utils/color.js' {
  declare module.exports: $Exports<'react-native-floating-action/src/utils/color'>;
}
declare module 'react-native-floating-action/src/utils/platform.js' {
  declare module.exports: $Exports<'react-native-floating-action/src/utils/platform'>;
}
declare module 'react-native-floating-action/src/utils/touchable.js' {
  declare module.exports: $Exports<'react-native-floating-action/src/utils/touchable'>;
}
