// flow-typed signature: e14992e29081bc1cd21c59d63596e42b
// flow-typed version: <<STUB>>/react-native-localize_v1.1.4/flow_v0.92.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-localize'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-localize' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-native-localize/index' {
  declare module.exports: $Exports<'react-native-localize'>;
}
declare module 'react-native-localize/index.js' {
  declare module.exports: $Exports<'react-native-localize'>;
}
