// flow-typed signature: dec77d86bc333d0fe1af7d2ef253b045
// flow-typed version: <<STUB>>/react-native-picker-select_v6.3.3/flow_v0.92.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-picker-select'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-picker-select' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-picker-select/src' {
  declare module.exports: any;
}

declare module 'react-native-picker-select/src/styles' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-picker-select/src/index' {
  declare module.exports: $Exports<'react-native-picker-select/src'>;
}
declare module 'react-native-picker-select/src/index.js' {
  declare module.exports: $Exports<'react-native-picker-select/src'>;
}
declare module 'react-native-picker-select/src/styles.js' {
  declare module.exports: $Exports<'react-native-picker-select/src/styles'>;
}
