// flow-typed signature: 03f1402c910a112815755da47ee2e089
// flow-typed version: <<STUB>>/@react-native-community/datetimepicker_v2.1.0/flow_v0.92.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@react-native-community/datetimepicker'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@react-native-community/datetimepicker' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@react-native-community/datetimepicker/example/App' {
  declare module.exports: any;
}

declare module '@react-native-community/datetimepicker/example/e2e/detoxTest.spec' {
  declare module.exports: any;
}

declare module '@react-native-community/datetimepicker/example/e2e/init' {
  declare module.exports: any;
}

declare module '@react-native-community/datetimepicker/example' {
  declare module.exports: any;
}

declare module '@react-native-community/datetimepicker/flow-typed/npm/invariant_v2.x.x' {
  declare module.exports: any;
}

declare module '@react-native-community/datetimepicker/jest.config' {
  declare module.exports: any;
}

declare module '@react-native-community/datetimepicker/react-native.config' {
  declare module.exports: any;
}

declare module '@react-native-community/datetimepicker/src/constants' {
  declare module.exports: any;
}

declare module '@react-native-community/datetimepicker/src/datepicker.android' {
  declare module.exports: any;
}

declare module '@react-native-community/datetimepicker/src/datetimepicker.android' {
  declare module.exports: any;
}

declare module '@react-native-community/datetimepicker/src/datetimepicker.ios' {
  declare module.exports: any;
}

declare module '@react-native-community/datetimepicker/src' {
  declare module.exports: any;
}

declare module '@react-native-community/datetimepicker/src/picker.android' {
  declare module.exports: any;
}

declare module '@react-native-community/datetimepicker/src/picker.ios' {
  declare module.exports: any;
}

declare module '@react-native-community/datetimepicker/src/timepicker.android' {
  declare module.exports: any;
}

declare module '@react-native-community/datetimepicker/src/types' {
  declare module.exports: any;
}

declare module '@react-native-community/datetimepicker/src/utils' {
  declare module.exports: any;
}

declare module '@react-native-community/datetimepicker/test/constants.test' {
  declare module.exports: any;
}

declare module '@react-native-community/datetimepicker/test/index.test' {
  declare module.exports: any;
}

declare module '@react-native-community/datetimepicker/test/utils.test' {
  declare module.exports: any;
}

// Filename aliases
declare module '@react-native-community/datetimepicker/example/App.js' {
  declare module.exports: $Exports<'@react-native-community/datetimepicker/example/App'>;
}
declare module '@react-native-community/datetimepicker/example/e2e/detoxTest.spec.js' {
  declare module.exports: $Exports<'@react-native-community/datetimepicker/example/e2e/detoxTest.spec'>;
}
declare module '@react-native-community/datetimepicker/example/e2e/init.js' {
  declare module.exports: $Exports<'@react-native-community/datetimepicker/example/e2e/init'>;
}
declare module '@react-native-community/datetimepicker/example/index' {
  declare module.exports: $Exports<'@react-native-community/datetimepicker/example'>;
}
declare module '@react-native-community/datetimepicker/example/index.js' {
  declare module.exports: $Exports<'@react-native-community/datetimepicker/example'>;
}
declare module '@react-native-community/datetimepicker/flow-typed/npm/invariant_v2.x.x.js' {
  declare module.exports: $Exports<'@react-native-community/datetimepicker/flow-typed/npm/invariant_v2.x.x'>;
}
declare module '@react-native-community/datetimepicker/jest.config.js' {
  declare module.exports: $Exports<'@react-native-community/datetimepicker/jest.config'>;
}
declare module '@react-native-community/datetimepicker/react-native.config.js' {
  declare module.exports: $Exports<'@react-native-community/datetimepicker/react-native.config'>;
}
declare module '@react-native-community/datetimepicker/src/constants.js' {
  declare module.exports: $Exports<'@react-native-community/datetimepicker/src/constants'>;
}
declare module '@react-native-community/datetimepicker/src/datepicker.android.js' {
  declare module.exports: $Exports<'@react-native-community/datetimepicker/src/datepicker.android'>;
}
declare module '@react-native-community/datetimepicker/src/datetimepicker.android.js' {
  declare module.exports: $Exports<'@react-native-community/datetimepicker/src/datetimepicker.android'>;
}
declare module '@react-native-community/datetimepicker/src/datetimepicker.ios.js' {
  declare module.exports: $Exports<'@react-native-community/datetimepicker/src/datetimepicker.ios'>;
}
declare module '@react-native-community/datetimepicker/src/index' {
  declare module.exports: $Exports<'@react-native-community/datetimepicker/src'>;
}
declare module '@react-native-community/datetimepicker/src/index.js' {
  declare module.exports: $Exports<'@react-native-community/datetimepicker/src'>;
}
declare module '@react-native-community/datetimepicker/src/picker.android.js' {
  declare module.exports: $Exports<'@react-native-community/datetimepicker/src/picker.android'>;
}
declare module '@react-native-community/datetimepicker/src/picker.ios.js' {
  declare module.exports: $Exports<'@react-native-community/datetimepicker/src/picker.ios'>;
}
declare module '@react-native-community/datetimepicker/src/timepicker.android.js' {
  declare module.exports: $Exports<'@react-native-community/datetimepicker/src/timepicker.android'>;
}
declare module '@react-native-community/datetimepicker/src/types.js' {
  declare module.exports: $Exports<'@react-native-community/datetimepicker/src/types'>;
}
declare module '@react-native-community/datetimepicker/src/utils.js' {
  declare module.exports: $Exports<'@react-native-community/datetimepicker/src/utils'>;
}
declare module '@react-native-community/datetimepicker/test/constants.test.js' {
  declare module.exports: $Exports<'@react-native-community/datetimepicker/test/constants.test'>;
}
declare module '@react-native-community/datetimepicker/test/index.test.js' {
  declare module.exports: $Exports<'@react-native-community/datetimepicker/test/index.test'>;
}
declare module '@react-native-community/datetimepicker/test/utils.test.js' {
  declare module.exports: $Exports<'@react-native-community/datetimepicker/test/utils.test'>;
}
